services:
  selenium-hub:
    image: selenium/hub:4.18.1
    networks:
      - selenium-net

  chrome:
    image: selenium/node-chrome:4.18.1
    depends_on:
      - selenium-hub
    networks:
      - selenium-net

  firefox:
    image: selenium/node-firefox:4.18.1
    depends_on:
      - selenium-hub
    networks:
      - selenium-net
